[tool.poetry]
name = "python-virtual-env"
version = "0.1.0"
description = ""
authors = ["Daniel Arcanjo <daniel.thomas.aarcanjo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
